/*
  # Parent Portal System

  Allows parents to link to student accounts, track progress,
  and provide incentives for completed goals.
*/

-- Parent-student links
CREATE TABLE IF NOT EXISTS parent_links (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  parent_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  student_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  link_code TEXT NOT NULL UNIQUE,
  is_active BOOLEAN DEFAULT true,
  relationship TEXT DEFAULT 'parent',
  approved_at TIMESTAMPTZ,
  UNIQUE(parent_user_id, student_user_id)
);

ALTER TABLE parent_links ENABLE ROW LEVEL SECURITY;

-- Parents can see their links
CREATE POLICY "Parents view own links" ON parent_links FOR SELECT
  TO authenticated USING (auth.uid() = parent_user_id OR auth.uid() = student_user_id);

-- Only insert with valid link code
CREATE POLICY "Insert parent link" ON parent_links FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = parent_user_id);

-- Incentives (rewards parents create for students)
CREATE TABLE IF NOT EXISTS incentives (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  parent_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  student_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  incentive_type TEXT DEFAULT 'message',
  goal_type TEXT DEFAULT 'manual',
  goal_target INTEGER,
  goal_progress INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending',
  unlocked_at TIMESTAMPTZ,
  redeemed_at TIMESTAMPTZ,
  message_content TEXT,
  linked_task_id UUID,
  linked_exam_id UUID,
  linked_timer_sessions INTEGER DEFAULT 0
);

ALTER TABLE incentives ENABLE ROW LEVEL SECURITY;

CREATE POLICY "View own incentives" ON incentives FOR SELECT
  TO authenticated USING (auth.uid() = parent_user_id OR auth.uid() = student_user_id);

CREATE POLICY "Parents create incentives" ON incentives FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = parent_user_id);

CREATE POLICY "Parents update incentives" ON incentives FOR UPDATE
  TO authenticated USING (auth.uid() = parent_user_id OR auth.uid() = student_user_id);

-- Parent notifications
CREATE TABLE IF NOT EXISTS parent_notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  parent_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  student_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT,
  related_entity_id UUID,
  related_entity_type TEXT,
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMPTZ
);

ALTER TABLE parent_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Parents view notifications" ON parent_notifications FOR SELECT
  TO authenticated USING (auth.uid() = parent_user_id);

CREATE POLICY "Parents update notifications" ON parent_notifications FOR UPDATE
  TO authenticated USING (auth.uid() = parent_user_id);

-- Student notifications (for incentives received)
CREATE TABLE IF NOT EXISTS student_notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  student_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT,
  related_incentive_id UUID REFERENCES incentives(id) ON DELETE SET NULL,
  is_read BOOLEAN DEFAULT false,
  read_at TIMESTAMPTZ
);

ALTER TABLE student_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Students view notifications" ON student_notifications FOR SELECT
  TO authenticated USING (auth.uid() = student_user_id);

CREATE POLICY "Students update notifications" ON student_notifications FOR UPDATE
  TO authenticated USING (auth.uid() = student_user_id);

-- Link codes (generated by students for parents to use)
CREATE TABLE IF NOT EXISTS link_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  student_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ,
  used_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true
);

ALTER TABLE link_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Students manage codes" ON link_codes FOR ALL
  TO authenticated USING (auth.uid() = student_user_id);

-- Indexes
CREATE INDEX idx_parent_links_parent ON parent_links(parent_user_id);
CREATE INDEX idx_parent_links_student ON parent_links(student_user_id);
CREATE INDEX idx_incentives_student ON incentives(student_user_id);
CREATE INDEX idx_parent_notifications_parent ON parent_notifications(parent_user_id);
CREATE INDEX idx_student_notifications_student ON student_notifications(student_user_id);
